---
# tasks file for raspbian-compose

- name: Install Docker Compose via pip
  become: yes
  pip:
      name: docker-compose=={{ raspbian_compose_version }}
      virtualenv_python: undefined
      state: present
      version: "{{ raspbian_compose_version }}"
