---
# tasks file for raspbian-compose

- name: Install pip
  become: yes
  apt:
    update_cache: yes
    state: present
    name: "python-pip=9.0.1-2+rpt2"

- name: Install Docker Compose via pip
  become: yes
  pip:
      name: docker-compose
      state: present
      version: "{{ raspbian_compose_version }}"
